import { Speaker } from '@types';

export const SPEAKERS: Speaker[] = [
  {
    company: `Ethereum Foundation`,
    firstname: `Martin`,
    lastname: `Lundfall`,
    link: `https://twitter.com/martinlundfall`,
    picture: `/speakers/Martin_Lundfall.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Tim`,
    lastname: `Beiko`,
    link: `https://twitter.com/timbeiko`,
    picture: `/speakers/Tim_Beiko.jpg`,
  },
  {
    company: `The Graph`,
    firstname: `Tegan`,
    lastname: `Kline`,
    link: `https://twitter.com/theklineventure`,
    picture: `/speakers/Tegan_Kline.jpg`,
  },
  {
    company: `ENS`,
    firstname: `Makoto`,
    lastname: `Inoue`,
    link: `https://twitter.com/makoto_inoue`,
    picture: `/speakers/Makoto_Inoue.jpg`,
  },
  {
    company: `hermez.io`,
    firstname: `Jordi`,
    lastname: `Baylina`,
    link: `https://twitter.com/jbaylina`,
    picture: `/speakers/Jordi_Baylina.jpg`,
  },
  {
    company: `AAVE`,
    firstname: `Emilio`,
    lastname: `Frangella`,
    link: `https://twitter.com/The3D_`,
    picture: `/speakers/Emilio_Frangela.jpg`,
  },
  {
    company: `Monolith`,
    firstname: `Mel`,
    lastname: `Gelderman`,
    link: `https://twitter.com/monolith_web3`,
    picture: `/speakers/Mel_Gelderman.jpg`,
  },
  {
    company: `BloxStaking.com`,
    firstname: `Alon `,
    lastname: `Muroch`,
    link: `https://twitter.com/AmMuroch`,
    picture: `/speakers/Alon_Muroch.jpg`,
  },
  {
    company: `Concordia University`,
    firstname: `Mahsa`,
    lastname: `Moosavi`,
    link: `https://twitter.com/msv_mahsa`,
    picture: `/speakers/Mahsa_Moosavi.jpg`,
  },
  {
    company: `Open Zeppelin`,
    firstname: `Hadrien`,
    lastname: `Croubois`,
    link: `https://twitter.com/Amxx`,
    picture: `/speakers/Hadrien_Croubois.jpg`,
  },
  {
    company: `Streamr`,
    firstname: `Henri`,
    lastname: `Pihkala`,
    link: `https://twitter.com/henripihkala`,
    picture: `/speakers/Henri_Pihkala.jpg`,
  },
  {
    company: `Winding Tree`,
    firstname: `Maksim`,
    lastname: `Izmaylov`,
    link: `https://twitter.com/kvakes`,
    picture: `/speakers/Maksim_Izmaylov.jpg`,
  },
  {
    company: `WalletConnect`,
    firstname: `Pedro`,
    lastname: `Gomes`,
    link: `https://twitter.com/pedrouid`,
    picture: `/speakers/Pedro_Gomes.jpg`,
  },
  {
    company: `Status`,
    firstname: `Simona`,
    lastname: `Pop`,
    link: `https://twitter.com/Sim_Pop`,
    picture: `/speakers/Simona_Pop.jpg`,
  },
  {
    company: `Linum Labs`,
    firstname: `Paula`,
    lastname: `Pettit`,
    link: `https://twitter.com/paulapbpb`,
    picture: `/speakers/Paula_Pettit.jpg`,
  },
  {
    company: `Aave`,
    firstname: `Stani`,
    lastname: `Kulechov`,
    link: `https://twitter.com/StaniKulechov`,
    picture: `/speakers/Stani_Kulechov.jpg`,
  },
  {
    company: `Monolith`,
    firstname: `Riccardo`,
    lastname: `Persiani`,
    link: `https://www.linkedin.com/in/riccardo-persiani/`,
    picture: `/speakers/Riccardo_Persiani.jpg`,
  },
  {
    company: `ConsenSys`,
    firstname: `Nick`,
    lastname: `Kritikos`,
    link: `https://twitter.com/Kritikos`,
    picture: `/speakers/Nick_Kritikos.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Christian`,
    lastname: `Reitwiessner`,
    link: `https://twitter.com/twitter.com/ethchris`,
    picture: `/speakers/Christian_Reitwiessner.jpg`,
  },
  {
    company: `ConsenSys Diligence / Concordia University`,
    firstname: `Shayan`,
    lastname: `Eskandari`,
    link: `https://shayan.es`,
    picture: `/speakers/Shayan_Eskandari.jpg`,
  },
  {
    company: `DAppNode`,
    firstname: `Eduardo`,
    lastname: `Antuña`,
    link: `https://twitter.com/eduadiez`,
    picture: `/speakers/Eduardo_Antuna.jpg`,
  },
  {
    company: ` Near Foundation`,
    firstname: `Sonja`,
    lastname: `Prstec`,
    link: `https://www.linkedin.com/in/sonja-prstec-mag-iur-89a0b324/`,
    picture: `/speakers/Sonja_Prstec.jpg`,
  },
  {
    company: `Furucombo`,
    firstname: `Chu`,
    lastname: `Hsuan-Ting`,
    link: `https://twitter.com/hsuantingchu`,
    picture: `/speakers/Chu_Hsuan-Ting.jpg`,
  },
  {
    company: `Web3 Foundation`,
    firstname: `Bruno`,
    lastname: `Škvorc`,
    link: `https://twitter.com/bitfalls`,
    picture: `/speakers/Bruno_Skvorc.jpg`,
  },
  {
    company: `NonFungible.com`,
    firstname: `Gauthier`,
    lastname: `Zuppinger`,
    link: `https://twitter.com/Gauthier_Z`,
    picture: `/speakers/Gauthier_Zuppinger.jpg`,
  },
  {
    company: `Axie Infinity`,
    firstname: `Aleksander`,
    lastname: `Larsen`,
    link: `https://twitter.com/twitter.com/psycheout86`,
    picture: `/speakers/Aleksander_Larsen.jpg`,
  },
  {
    company: `Orchid`,
    firstname: `Dr. Steven`,
    lastname: `Waterhouse `,
    link: `https://twitter.com/deseventral`,
    picture: `/speakers/Steven_Waterhouse.jpg`,
  },
  {
    company: `General Protocols`,
    firstname: `Rosco`,
    lastname: `Kalis`,
    link: `https://twitter.com/RoscoKalis`,
    picture: `/speakers/Rosco_Kalis.jpg`,
  },
  {
    company: `ConsenSys Diligence`,
    firstname: `Brianna`,
    lastname: `Montgomery`,
    link: `https://twitter.com/consensysaudits`,
    picture: `/speakers/Brianna_Montgomery.jpg`,
  },
  {
    company: `GoodDollar.org`,
    firstname: `Anna`,
    lastname: `Stone`,
    link: `https://www.linkedin.com/in/annalstone/`,
    picture: `/speakers/Anna_Stone.jpg`,
  },
  {
    company: `ChainSafe Systems`,
    firstname: `Aidan`,
    lastname: `Hyman`,
    link: `https://twitter.com/chainsafeth`,
    picture: `/speakers/Aidan_Hyman.jpg`,
  },
  {
    company: `Ethereum Explorer, Giveth, Commons Stack`,
    firstname: `Kris`,
    lastname: `Decoodt`,
    link: `https://twitter.com/@krrisis`,
    picture: `/speakers/Kris_Decoodt.jpg`,
  },
  {
    company: `Tellor`,
    firstname: `Brenda`,
    lastname: `Loya`,
    link: `https://twitter.com/justbrendax`,
    picture: `/speakers/Brenda_Loya.jpg`,
  },
  {
    company: `Blockchains LLC`,
    firstname: `Christoph`,
    lastname: `Jentzsch`,
    link: `https://twitter.com/ChrJentzsch`,
    picture: `/speakers/Christoph_Jentzsch.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Franziska`,
    lastname: `Heintel`,
    link: `https://twitter.com/_franzihei`,
    picture: `/speakers/Franziska_Heintel.jpg`,
  },
  {
    company: `Radicle`,
    firstname: `Abigael`,
    lastname: `Titcomb`,
    link: `https://twitter.com/abbey_titcomb`,
    picture: `/speakers/Abigael_Titcomb.jpg`,
  },
  {
    company: `AVADO`,
    firstname: `Stefaan`,
    lastname: `Ponnet`,
    link: `https://twitter.com/AvadoCloud`,
    picture: `/speakers/Stefaan_Ponnet.jpg`,
  },
  {
    company: `DeversiFi`,
    firstname: `Will`,
    lastname: `Harborne`,
    link: `https://twitter.com/will_harborne`,
    picture: `/speakers/Will_Harborne.jpg`,
  },
  {
    company: `Kaiko`,
    firstname: `Ambre`,
    lastname: `Soubiran`,
    link: `https://twitter.com/ambresoub`,
    picture: `/speakers/Ambre_Soubiran.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `William`,
    lastname: `George`,
    link: `https://twitter.com/williamhwgeorge`,
    picture: `/speakers/William_George.jpg`,
  },
  {
    company: `Aave`,
    firstname: `Ajit kumar`,
    lastname: `Tripathi`,
    link: `https://twitter.com/chainyoda`,
    picture: `/speakers/Ajit_Kumar_Tripathi.jpg`,
  },
  {
    company: `Kaiko`,
    firstname: `Clara`,
    lastname: `Medalie`,
    link: `https://twitter.com/Clara_Medalie`,
    picture: `/speakers/Clara_Medalie.jpg`,
  },
  {
    company: `Pool Foundation`,
    firstname: `Shiv`,
    lastname: `Malik`,
    link: `https://twitter.com/shivmalik`,
    picture: `/speakers/Shiv_Malik.jpg`,
  },
  {
    company: `INATBA`,
    firstname: `Marc`,
    lastname: `Taverner`,
    link: `https://twitter.com/blocktav`,
    picture: `/speakers/Marc_Taverner.jpg`,
  },
  {
    company: `LedgerPrime`,
    firstname: `Ayesha`,
    lastname: `Kiani`,
    link: `https://www.linkedin.com/in/ayeshakiani/`,
    picture: `/speakers/Ayesha_Kiani.jpg`,
  },
  {
    company: `cLabs`,
    firstname: `Markus`,
    lastname: `Franke`,
    link: `https://www.linkedin.com/in/markus-f-82242028/`,
    picture: `/speakers/Markus_Franke.jpg`,
  },
  {
    company: `BPCE`,
    firstname: `Cyril`,
    lastname: `Vignet`,
    link: `https://www.linkedin.com/in/cyril-vignet-423704bb/`,
    picture: `/speakers/Cyril_Vignet.jpg`,
  },
  {
    company: `LazyLedger`,
    firstname: `John`,
    lastname: `Adler`,
    link: `https://twitter.com/jadler0`,
    picture: `/speakers/John_Adler.jpg`,
  },
  {
    company: `SKALE Labs`,
    firstname: `Konstatin`,
    lastname: `Kladko`,
    link: `https://twitter.com/Stan_Kladko`,
    picture: `/speakers/Konstatin_Kladko.jpg`,
  },
  {
    company: `Grassroots Economics`,
    firstname: `Rebecca`,
    lastname: `Mqamelo`,
    link: `https://twitter.com/Rebecca_Mqamelo`,
    picture: `/speakers/Rebecca_Mqamelo.jpg`,
  },
  {
    company: `Ethereum Push Notification Service (EPNS)`,
    firstname: `Harsh`,
    lastname: `Rajat`,
    link: `https://twitter.com/harshrajat`,
    picture: `/speakers/Harsh_Rajat.jpg`,
  },
  {
    company: `Arianee`,
    firstname: `Luc`,
    lastname: `Jodet`,
    link: `https://twitter.com/lucjodet`,
    picture: `/speakers/Luc_Jodet.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `Ferit`,
    lastname: `Tuncer`,
    link: `https://twitter.com/0xferittuncer`,
    picture: `/speakers/Ferit_Tuncer.jpg`,
  },
  {
    company: `YAP Global`,
    firstname: `Samantha`,
    lastname: `Yap`,
    link: `https://twitter.com/samanthawyap`,
    picture: `/speakers/Samantha_Yap.jpg`,
  },
  {
    company: `Cooperative Kleros`,
    firstname: `Federico`,
    lastname: `Ast`,
    link: `https://twitter.com/federicoast`,
    picture: `/speakers/Federico_Ast.jpg`,
  },
  {
    company: `Kaiko`,
    firstname: `Sacha`,
    lastname: `Ghebali`,
    link: `https://twitter.com/sgheb`,
    picture: `/speakers/Sacha_Ghebali.jpg`,
  },
  {
    company: `IOVLabs`,
    firstname: `Solange`,
    lastname: `Gueiros`,
    link: `https://www.linkedin.com/in/solangegueiros/`,
    picture: `/speakers/Solange_Gueiros.jpg`,
  },
  {
    company: `Infrachain`,
    firstname: `Fabrice`,
    lastname: `Croiseaux`,
    link: `https://www.linkedin.com/in/fcroiseaux/`,
    picture: `/speakers/Fabrice_Croiseaux.jpg`,
  },
  {
    company: `Witnet Foundation`,
    firstname: `Claudia`,
    lastname: `Bartoli`,
    link: `https://www.linkedin.com/in/claudia-bartoli/`,
    picture: `/speakers/Claudia_Bartoli.jpg`,
  },
  {
    company: `iExec`,
    firstname: `Gilles`,
    lastname: `Fedak`,
    link: `https://twitter.com/iex_ec`,
    picture: `/speakers/Gilles_Fedak.jpg`,
  },
  {
    company: `Ethereum France`,
    firstname: `Nathan`,
    lastname: `Sexer`,
    link: `https://twitter.com/NathanSexer`,
    picture: `/speakers/Nathan_Sexer.jpg`,
  },
  {
    company: `Fountain`,
    firstname: `Mathieu`,
    lastname: `Chanson`,
    link: `https://www.linkedin.com/in/mathieuchanson/`,
    picture: `/speakers/Mathieu_Chanson.jpg`,
  },
  {
    company: `pNetwork`,
    firstname: `Thomas`,
    lastname: `Bertani`,
    link: `https://twitter.com/ThomasBertani`,
    picture: `/speakers/Thomas_Bertani.jpg`,
  },
  {
    company: `Nexo`,
    firstname: `Nikolay`,
    lastname: `Angelov`,
    link: `https://www.linkedin.com/in/thedi/`,
    picture: `/speakers/Nikolay_Angelov.jpg`,
  },
  {
    company: `Visa Research`,
    firstname: `Srinivasan`,
    lastname: `Raghuraman`,
    link: `https://twitter.com/srini131293`,
    picture: `/speakers/Srinivasan_Raghuraman.jpg`,
  },
  {
    company: `Keep Network`,
    firstname: `Sasha`,
    lastname: `Tanase`,
    link: `https://twitter.com/sasha_tanase`,
    picture: `/speakers/Sasha_Tanase.jpg`,
  },
  {
    company: `Democracy Earth Foundation`,
    firstname: `Santiago`,
    lastname: `Siri`,
    link: `https://twitter.com/santisiri`,
    picture: `/speakers/Santiago_Siri.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Barnabe`,
    lastname: `Monnot`,
    link: `https://twitter.com/barnabemonnot`,
    picture: `/speakers/Barnabe_Monnot.jpg`,
  },
  {
    company: `Bitwala`,
    firstname: `Benjamin`,
    lastname: `Jones`,
    link: `https://twitter.com/BenPeterJones`,
    picture: `/speakers/Benjamin_Jones.jpg`,
  },
  {
    company: `Consensys`,
    firstname: `Sajida`,
    lastname: `Zouarhi`,
    link: `https://twitter.com/Saj_JZ`,
    picture: `/speakers/Sajida_Zouarhi.jpg`,
  },
  {
    company: `Gnosis Safe`,
    firstname: `Richard`,
    lastname: `Meissner`,
    link: `https://twitter.com/rimeissner`,
    picture: `/speakers/Richard_Meissner.jpg`,
  },
  {
    company: `Etherplay`,
    firstname: `Ronan`,
    lastname: `Sandford`,
    link: `https://twitter.com/wighawag`,
    picture: `/speakers/Ronan_Sandford.jpg`,
  },
  {
    company: `Amazon Web Services`,
    firstname: `Everton`,
    lastname: `Fraga`,
    link: `https://twitter.com/evertonfraga`,
    picture: `/speakers/Everton_Fraga.jpg`,
  },
  {
    company: `Harvard / CNRS`,
    firstname: `Primavera`,
    lastname: `De filippi`,
    link: `https://twitter.com/yaoeo`,
    picture: `/speakers/Primavera_De_Filippi.jpg`,
  },
  {
    company: `Multis`,
    firstname: `Thibaut`,
    lastname: `Sahaghian`,
    link: `https://www.linkedin.com/in/tsahaghian/`,
    picture: `/speakers/Thibaut_Sahaghian.jpg`,
  },
  {
    company: `Sushi.com`,
    firstname: `Joseph`,
    lastname: `Delong`,
    link: `https://twitter.com/josephdelong`,
    picture: `/speakers/Joseph_Delong.jpg`,
  },
  {
    company: `L2P.finance`,
    firstname: `Alexis`,
    lastname: `Masseron`,
    link: `https://twitter.com/AlexisMasseron`,
    picture: `/speakers/Alexis_Masseron.jpg`,
  },
  {
    company: `Ledger`,
    firstname: `Matt`,
    lastname: `Johnson`,
    link: `https://www.ledger.com/people/matt-johnson`,
    picture: `/speakers/Matt_Johnson.jpg`,
  },
  {
    company: `Ledger`,
    firstname: `Jean`,
    lastname: `Passot`,
    link: `https://www.linkedin.com/in/jean-p-68100312a/`,
    picture: `/speakers/Jean_Passot.jpg`,
  },
  {
    company: `Stake Capital`,
    firstname: `Julien`,
    lastname: `Bouteloup`,
    link: `https://twitter.com/bneiluj`,
    picture: `/speakers/Julien_Bouteloup.jpg`,
  },
  {
    company: `Boson Protocol`,
    firstname: `Holly`,
    lastname: `Atkinson`,
    link: `https://twitter.com/haatkinson`,
    picture: `/speakers/Holly_Atkinson.jpg`,
  },
  {
    company: `rotki`,
    firstname: `Lefteris`,
    lastname: `Karapetsas`,
    link: `https://twitter.com/lefterisjp`,
    picture: `/speakers/Lefteris_Karapetsas.jpg`,
  },
  {
    company: `Paladin`,
    firstname: `Romain`,
    lastname: `Figuereo`,
    link: `https://twitter.com/Figue_me`,
    picture: `/speakers/Romain_Figuereo.jpg`,
  },
  {
    company: `Chainlink`,
    firstname: `Johann`,
    lastname: `Eid`,
    link: `https://twitter.com/EidJohann`,
    picture: `/speakers/Johann_Eid.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `Matheus`,
    lastname: `Alencar`,
    link: `https://twitter.com/mtsalenc`,
    picture: `/speakers/Matheus_Alencar.jpg`,
  },
  {
    company: `Fei Protocol`,
    firstname: `Joey`,
    lastname: `Santoro`,
    link: `https://twitter.com/Joey__Santoro`,
    picture: `/speakers/Joey_Santoro.jpg`,
  },
  {
    company: `ECAN`,
    firstname: `Xavier`,
    lastname: `Lavayssiere`,
    link: `https://twitter.com/xavierlava`,
    picture: `/speakers/Xavier_Lavayssiere.jpg`,
  },
  {
    company: `EidooCard`,
    firstname: `Michele`,
    lastname: `Montecchi`,
    link: `https://www.linkedin.com/in/michele-montecchi-b8025921/`,
    picture: `/speakers/Michele_Montecchi.jpg`,
  },
  {
    company: `Tel Aviv University and Certora`,
    firstname: `Mooly`,
    lastname: `Sagiv`,
    link: `https://twitter.com/SagivMooly`,
    picture: `/speakers/Mooly_Sagiv.jpg`,
  },
  {
    company: `Gelato`,
    firstname: `Hilmar`,
    lastname: `Orth`,
    link: `https://twitter.com/hilmarxo`,
    picture: `/speakers/Hilmar_Orth.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `Plinio`,
    lastname: `Braga`,
    link: `https://twitter.com/pliniobraga_`,
    picture: `/speakers/Plinio_Braga.jpg`,
  },
  {
    company: `MIT Media Lab`,
    firstname: `Daniel`,
    lastname: `Marquez`,
    link: `https://twitter.com/Bumangues92`,
    picture: `/speakers/Daniel_Marquez.jpg`,
  },
  {
    company: `Storj Labs`,
    firstname: `Kevin`,
    lastname: `Leffew`,
    link: `https://www.linkedin.com/in/kevinleffew/`,
    picture: `/speakers/Kevin_Leffew.jpg`,
  },
  {
    company: `Commonwealth Labs`,
    firstname: `Drew`,
    lastname: `Stone`,
    link: `https://twitter.com/drew___stone`,
    picture: `/speakers/Drew_Stone.jpg`,
  },
  {
    company: `NuCypher`,
    firstname: `Ravital`,
    lastname: `Solomon`,
    link: `https://www.linkedin.com/in/ravital/`,
    picture: `/speakers/Ravital_Solomon.jpg`,
  },
  {
    company: `Crypto art advisor and collector`,
    firstname: `Fanny`,
    lastname: `Lakoubay`,
    link: `https://twitter.com/twitter.com/flakoubay`,
    picture: `/speakers/Fanny_Lakoubay.jpg`,
  },
  {
    company: `European Investment Fund`,
    firstname: `Rene`,
    lastname: `Andres`,
    link: `https://www.linkedin.com/in/ren%C3%A9-andres-663457aa/`,
    picture: `/speakers/Rene_Andres.jpg`,
  },
  {
    company: `Ethertrust`,
    firstname: `Pascal`,
    lastname: `Urien`,
    link: `https://www.linkedin.com/in/pascal-urien-a491738`,
    picture: `/speakers/Pascal_Urien.jpg`,
  },
  {
    company: `Biconomy `,
    firstname: `Ahmed`,
    lastname: `Al-balaghi`,
    link: `https://twitter.com/arabalaghi`,
    picture: `/speakers/Ahmed_Al-balaghi.jpg`,
  },
  {
    company: `1inch Network`,
    firstname: `Anton`,
    lastname: `Bukov`,
    link: `https://twitter.com/k06a`,
    picture: `/speakers/Anton_Bukov.jpg`,
  },
  {
    company: `Harmony`,
    firstname: `Stephen`,
    lastname: `Tse`,
    link: `https://twitter.com/stse`,
    picture: `/speakers/Stephen_Tse.jpg`,
  },
  {
    company: `Techintern.io`,
    firstname: `Kingsong`,
    lastname: `Chen`,
    link: `https://www.linkedin.com/in/kingsong/`,
    picture: `/speakers/Kingsong_Chen.jpg`,
  },
  {
    company: `Autonomous lawyer`,
    firstname: `Fatemeh`,
    lastname: `Fannizadeh`,
    link: `https://twitter.com/fatalmeh`,
    picture: `/speakers/Fatemeh_Fannizadeh.jpg`,
  },
  {
    company: `Opera`,
    firstname: `Susie`,
    lastname: `Batt`,
    link: `https://www.linkedin.com/in/susiebatt/`,
    picture: `/speakers/Susie_Batt.jpg`,
  },
  {
    company: `Blockchangers`,
    firstname: `Jon`,
    lastname: `Ramvi`,
    link: `https://twitter.com/JonRamvi`,
    picture: `/speakers/Jon_Ramvi.jpg`,
  },
  {
    company: `TrueBlocks, LLC`,
    firstname: `Thomas-Jay`,
    lastname: `Rush`,
    link: `https://twitter.com/trueblocks`,
    picture: `/speakers/Thomas-Jay_Rush.jpg`,
  },
  {
    company: `Delphia`,
    firstname: `Allison`,
    lastname: `Reichel`,
    link: `https://twitter.com/AllisonReichel`,
    picture: `/speakers/Allison_Reichel.jpg`,
  },
  {
    company: `Filecoin Foundation`,
    firstname: `Marta`,
    lastname: `Belcher`,
    link: `https://twitter.com/martabelcher`,
    picture: `/speakers/Marta_Belcher.jpg`,
  },
  {
    company: `3Box Labs`,
    firstname: `Joel`,
    lastname: `Thorstensson`,
    link: `https://twitter.com/oedth`,
    picture: `/speakers/Joel_Thorstensson.jpg`,
  },
  {
    company: `GoodGhosting`,
    firstname: `Rachel`,
    lastname: `Black`,
    link: `https://twitter.com/rachblondon`,
    picture: `/speakers/Rachel_Black.jpg`,
  },
  {
    company: `Bitfly`,
    firstname: `Stefan`,
    lastname: `Starflinger`,
    link: `https://twitter.com/stefan_star`,
    picture: `/speakers/Stefan_Starflinger.jpg`,
  },
  {
    company: `HOPR`,
    firstname: `Amira`,
    lastname: `Bouguera`,
    link: `https://twitter.com/amirabouguera`,
    picture: `/speakers/Amira_Bouguera.jpg`,
  },
  {
    company: `https://web3api.dev`,
    firstname: `Jordan`,
    lastname: `Ellis`,
    link: `https://twitter.com/Web3API`,
    picture: `/speakers/Jordan_Ellis.jpg`,
  },
  {
    company: `Paraswap`,
    firstname: `Shresth`,
    lastname: `Agrawal`,
    link: `https://twitter.com/shresth3103`,
    picture: `/speakers/Shresth_Agrawal.jpg`,
  },
  {
    company: `EF`,
    firstname: `Austin`,
    lastname: `Griffith`,
    link: `https://twitter.com/austingriffith`,
    picture: `/speakers/Austin_Griffith.jpg`,
  },
  {
    company: `Centrifuge`,
    firstname: `Cassidy`,
    lastname: `Daly`,
    link: `https://twitter.com/cassidydaly`,
    picture: `/speakers/Cassidy_Daly.jpg`,
  },
  {
    company: `Nethermind`,
    firstname: `Tomasz`,
    lastname: `Stanczak`,
    link: `https://twitter.com/tkstanczak`,
    picture: `/speakers/Tomasz_Stanczak.jpg`,
  },
  {
    company: `Oiler Network`,
    firstname: `Victor`,
    lastname: `Naumik`,
    link: `https://twitter.com/vicnaum1`,
    picture: `/speakers/Victor_Naumik.jpg`,
  },
  {
    company: `Brainbot`,
    firstname: `Jannik`,
    lastname: `Luhn`,
    link: `https://twitter.com/AnotherJannik`,
    picture: `/speakers/Jannik_Luhn.jpg`,
  },
  {
    company: `Raiden Network`,
    firstname: `Jacob`,
    lastname: `Czepluch`,
    link: `https://twitter.com/_czepluch`,
    picture: `/speakers/Jacob_Czepluch.jpg`,
  },
  {
    company: `Gnosis`,
    firstname: `Felix`,
    lastname: `Leupold`,
    link: `https://twitter.com/fleupold_`,
    picture: `/speakers/Felix_Leupold.jpg`,
  },
  {
    company: `ConsenSys`,
    firstname: `James`,
    lastname: `Beck`,
    link: `https://twitter.com/jamesjohnbeck`,
    picture: `/speakers/James_Beck.jpg`,
  },
  {
    company: `Golem Network`,
    firstname: `Maria-Paula`,
    lastname: `Fernandez`,
    link: `https://twitter.com/@MPtherealMVP`,
    picture: `/speakers/Maria-Paula_Fernandez.jpg`,
  },
  {
    company: `The Mangrove`,
    firstname: `Vincent`,
    lastname: `Danos`,
    link: `https://twitter.com/vee3my`,
    picture: `/speakers/Vincent_Danos.jpg`,
  },
  {
    company: `MakerDAO`,
    firstname: `Gustav`,
    lastname: `Arentoft`,
    link: `https://twitter.com/GArentoft`,
    picture: `/speakers/Gustav_Arentoft.jpg`,
  },
  {
    company: `Charged Particles`,
    firstname: `Ben`,
    lastname: `Lakoff`,
    link: `https://twitter.com/benlakoff`,
    picture: `/speakers/Ben_Lakoff.jpg`,
  },
  {
    company: `APWine Finance`,
    firstname: `Gaspard`,
    lastname: `Peduzzi`,
    link: `https://twitter.com/GaspardPeduzzi`,
    picture: `/speakers/Gaspard_Peduzzi.jpg`,
  },
  {
    company: `Centrifuge/DoD`,
    firstname: `Helena`,
    lastname: `Flack`,
    link: `https://twitter.com/helsfoftroy`,
    picture: `/speakers/Helena_Flack.jpg`,
  },
  {
    company: `Celo`,
    firstname: `Marek`,
    lastname: `Olszewski`,
    link: `https://twitter.com/marek_`,
    picture: `/speakers/Marek_Olszewski.jpg`,
  },
  {
    company: `https://cosmos.network/`,
    firstname: `Peng`,
    lastname: `Zhong`,
    link: `https://twitter.com/zcpeng`,
    picture: `/speakers/Peng_Zhong.jpg`,
  },
  {
    company: `Offshift`,
    firstname: `Alex`,
    lastname: `Shipp`,
    link: `https://twitter.com/AlexShippXFT`,
    picture: `/speakers/Alex_Shipp.jpg`,
  },

  {
    company: `Outlier Ventures`,
    firstname: `Jamie`,
    lastname: `Burke`,
    link: `https://twitter.com/jamie247`,
    picture: `/speakers/Jamie_Burke.jpg`,
  },
  {
    company: `Travala`,
    firstname: `Juan`,
    lastname: `Otero`,
    link: `https://twitter.com/joterovila`,
    picture: `/speakers/Juan_Otero.jpg`,
  },
];
