import { Speaker } from '@types';

export const SPEAKERS: Speaker[] = [
  {
    company: `Anoma`,
    firstname: `Adrian`,
    lastname: `Brink`,
    link: `https://twitter.com/adrian_brink`,
    picture: `/speakers/Adrian_Brink.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Martin`,
    lastname: `Lundfall`,
    link: `https://twitter.com/martinlundfall`,
    picture: `/speakers/Martin_Lundfall.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Tim`,
    lastname: `Beiko`,
    link: `https://twitter.com/timbeiko`,
    picture: `/speakers/Tim_Beiko.jpg`,
  },
  {
    company: `ENS`,
    firstname: `Makoto`,
    lastname: `Inoue`,
    link: `https://twitter.com/makoto_inoue`,
    picture: `/speakers/Makoto_Inoue.jpg`,
  },
  {
    company: `hermez.io`,
    firstname: `Jordi`,
    lastname: `Baylina`,
    link: `https://twitter.com/jbaylina`,
    picture: `/speakers/Jordi_Baylina.jpg`,
  },
  {
    company: `AAVE`,
    firstname: `Ernesto`,
    lastname: `Boado`,
    link: `https://linkedin.com/in/ernesto-boado`,
    picture: `/speakers/Ernesto_Boado.jpg`,
  },
  {
    company: `Monolith`,
    firstname: `Mel`,
    lastname: `Gelderman`,
    link: `https://twitter.com/monolith_web3`,
    picture: `/speakers/Mel_Gelderman.jpg`,
  },
  {
    company: `BloxStaking.com`,
    firstname: `Alon `,
    lastname: `Muroch`,
    link: `https://twitter.com/AmMuroch`,
    picture: `/speakers/Alon_Muroch.jpg`,
  },
  {
    company: `Concordia University`,
    firstname: `Mahsa`,
    lastname: `Moosavi`,
    link: `https://twitter.com/msv_mahsa`,
    picture: `/speakers/Mahsa_Moosavi.jpg`,
  },
  {
    company: `Open Zeppelin`,
    firstname: `Hadrien`,
    lastname: `Croubois`,
    link: `https://twitter.com/Amxx`,
    picture: `/speakers/Hadrien_Croubois.jpg`,
  },
  {
    company: `Winding Tree`,
    firstname: `Maksim`,
    lastname: `Izmaylov`,
    link: `https://twitter.com/kvakes`,
    picture: `/speakers/Maksim_Izmaylov.jpg`,
  },
  {
    company: `WalletConnect`,
    firstname: `Pedro`,
    lastname: `Gomes`,
    link: `https://twitter.com/pedrouid`,
    picture: `/speakers/Pedro_Gomes.jpg`,
  },
  {
    company: `Status`,
    firstname: `Simona`,
    lastname: `Pop`,
    link: `https://twitter.com/Sim_Pop`,
    picture: `/speakers/Simona_Pop.jpg`,
  },
  {
    company: `Linum Labs`,
    firstname: `Paula`,
    lastname: `Pettit`,
    link: `https://twitter.com/paulapbpb`,
    picture: `/speakers/Paula_Pettit.jpg`,
  },
  {
    company: `Aave`,
    firstname: `Stani`,
    lastname: `Kulechov`,
    link: `https://twitter.com/StaniKulechov`,
    picture: `/speakers/Stani_Kulechov.jpg`,
  },
  {
    company: `Monolith`,
    firstname: `Riccardo`,
    lastname: `Persiani`,
    link: `https://www.linkedin.com/in/riccardo-persiani/`,
    picture: `/speakers/Riccardo_Persiani.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Christian`,
    lastname: `Reitwiessner`,
    link: `https://twitter.com/twitter.com/ethchris`,
    picture: `/speakers/Christian_Reitwiessner.jpg`,
  },
  {
    company: `DAppNode`,
    firstname: `Eduardo`,
    lastname: `Antuña`,
    link: `https://twitter.com/eduadiez`,
    picture: `/speakers/Eduardo_Antuna.jpg`,
  },
  {
    company: ` Near Foundation`,
    firstname: `Sonja`,
    lastname: `Prstec`,
    link: `https://www.linkedin.com/in/sonja-prstec-mag-iur-89a0b324/`,
    picture: `/speakers/Sonja_Prstec.jpg`,
  },
  {
    company: `Furucombo`,
    firstname: `Chu`,
    lastname: `Hsuan-Ting`,
    link: `https://twitter.com/hsuantingchu`,
    picture: `/speakers/Chu_Hsuan-Ting.jpg`,
  },
  {
    company: `RMRK`,
    firstname: `Bruno`,
    lastname: `Škvorc`,
    link: `https://twitter.com/bitfalls`,
    picture: `/speakers/Bruno_Skvorc.jpg`,
  },
  {
    company: `NonFungible.com`,
    firstname: `Gauthier`,
    lastname: `Zuppinger`,
    link: `https://twitter.com/Gauthier_Z`,
    picture: `/speakers/Gauthier_Zuppinger.jpg`,
  },
  {
    company: `Axie Infinity`,
    firstname: `Aleksander`,
    lastname: `Larsen`,
    link: `https://twitter.com/twitter.com/psycheout86`,
    picture: `/speakers/Aleksander_Larsen.jpg`,
  },
  {
    company: `Orchid`,
    firstname: `Dr. Steven`,
    lastname: `Waterhouse `,
    link: `https://twitter.com/deseventral`,
    picture: `/speakers/Steven_Waterhouse.jpg`,
  },
  {
    company: `General Protocols`,
    firstname: `Rosco`,
    lastname: `Kalis`,
    link: `https://twitter.com/RoscoKalis`,
    picture: `/speakers/Rosco_Kalis.jpg`,
  },
  {
    company: `ConsenSys Diligence`,
    firstname: `Brianna`,
    lastname: `Montgomery`,
    link: `https://twitter.com/consensysaudits`,
    picture: `/speakers/Brianna_Montgomery.jpg`,
  },
  {
    company: `GoodDollar.org`,
    firstname: `Tomer`,
    lastname: `Bariach`,
    link: `https://twitter.com/gooddollarorg`,
    picture: `/speakers/Tomer_Bariach.jpg`,
  },
  {
    company: `ChainSafe Systems`,
    firstname: `Aidan`,
    lastname: `Hyman`,
    link: `https://twitter.com/chainsafeth`,
    picture: `/speakers/Aidan_Hyman.jpg`,
  },
  {
    company: `Ethereum Explorer, Giveth, Commons Stack`,
    firstname: `Kris`,
    lastname: `Decoodt`,
    link: `https://twitter.com/@krrisis`,
    picture: `/speakers/Kris_Decoodt.jpg`,
  },
  {
    company: `Tellor`,
    firstname: `Brenda`,
    lastname: `Loya`,
    link: `https://twitter.com/justbrendax`,
    picture: `/speakers/Brenda_Loya.jpg`,
  },
  {
    company: `Self Employed`,
    firstname: `Christoph`,
    lastname: `Jentzsch`,
    link: `https://twitter.com/ChrJentzsch`,
    picture: `/speakers/Christoph_Jentzsch.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Franziska`,
    lastname: `Heintel`,
    link: `https://twitter.com/_franzihei`,
    picture: `/speakers/Franziska_Heintel.jpg`,
  },
  {
    company: `Radicle`,
    firstname: `Abigael`,
    lastname: `Titcomb`,
    link: `https://twitter.com/abbey_titcomb`,
    picture: `/speakers/Abigael_Titcomb.jpg`,
  },
  {
    company: `AVADO`,
    firstname: `Stefaan`,
    lastname: `Ponnet`,
    link: `https://twitter.com/AvadoCloud`,
    picture: `/speakers/Stefaan_Ponnet.jpg`,
  },
  {
    company: `DeversiFi`,
    firstname: `Will`,
    lastname: `Harborne`,
    link: `https://twitter.com/will_harborne`,
    picture: `/speakers/Will_Harborne.jpg`,
  },
  {
    company: `Kaiko`,
    firstname: `Ambre`,
    lastname: `Soubiran`,
    link: `https://twitter.com/ambresoub`,
    picture: `/speakers/Ambre_Soubiran.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `William`,
    lastname: `George`,
    link: `https://twitter.com/williamhwgeorge`,
    picture: `/speakers/William_George.jpg`,
  },
  {
    company: `Aave`,
    firstname: `Ajit kumar`,
    lastname: `Tripathi`,
    link: `https://twitter.com/chainyoda`,
    picture: `/speakers/Ajit_Kumar_Tripathi.jpg`,
  },
  {
    company: `Kaiko`,
    firstname: `Clara`,
    lastname: `Medalie`,
    link: `https://twitter.com/Clara_Medalie`,
    picture: `/speakers/Clara_Medalie.jpg`,
  },
  {
    company: `Pool Foundation`,
    firstname: `Shiv`,
    lastname: `Malik`,
    link: `https://twitter.com/shivmalik`,
    picture: `/speakers/Shiv_Malik.jpg`,
  },
  {
    company: `INATBA`,
    firstname: `Marc`,
    lastname: `Taverner`,
    link: `https://twitter.com/blocktav`,
    picture: `/speakers/Marc_Taverner.jpg`,
  },
  {
    company: `LedgerPrime`,
    firstname: `Ayesha`,
    lastname: `Kiani`,
    link: `https://www.linkedin.com/in/ayeshakiani/`,
    picture: `/speakers/Ayesha_Kiani.jpg`,
  },
  {
    company: `Celo`,
    firstname: `Markus`,
    lastname: `Franke`,
    link: `https://www.linkedin.com/in/markus-f-82242028/`,
    picture: `/speakers/Markus_Franke.jpg`,
  },
  {
    company: `BPCE`,
    firstname: `Cyril`,
    lastname: `Vignet`,
    link: `https://www.linkedin.com/in/cyril-vignet-423704bb/`,
    picture: `/speakers/Cyril_Vignet.jpg`,
  },
  {
    company: `Celestia Labs`,
    firstname: `John`,
    lastname: `Adler`,
    link: `https://twitter.com/jadler0`,
    picture: `/speakers/John_Adler.jpg`,
  },
  {
    company: `SKALE Labs`,
    firstname: `Konstantin`,
    lastname: `Kladko`,
    link: `https://twitter.com/Stan_Kladko`,
    picture: `/speakers/Konstantin_Kladko.jpg`,
  },
  {
    company: `Grassroots Economics`,
    firstname: `Rebecca`,
    lastname: `Mqamelo`,
    link: `https://twitter.com/Rebecca_Mqamelo`,
    picture: `/speakers/Rebecca_Mqamelo.jpg`,
  },
  {
    company: `Ethereum Push Notification Service (EPNS)`,
    firstname: `Harsh`,
    lastname: `Rajat`,
    link: `https://twitter.com/harshrajat`,
    picture: `/speakers/Harsh_Rajat.jpg`,
  },
  {
    company: `Arianee`,
    firstname: `Luc`,
    lastname: `Jodet`,
    link: `https://twitter.com/lucjodet`,
    picture: `/speakers/Luc_Jodet.jpg`,
  },
  {
    company: `YAP Global`,
    firstname: `Samantha`,
    lastname: `Yap`,
    link: `https://twitter.com/samanthawyap`,
    picture: `/speakers/Samantha_Yap.jpg`,
  },
  {
    company: `Cooperative Kleros`,
    firstname: `Federico`,
    lastname: `Ast`,
    link: `https://twitter.com/federicoast`,
    picture: `/speakers/Federico_Ast.jpg`,
  },
  {
    company: `Kaiko`,
    firstname: `Sacha`,
    lastname: `Ghebali`,
    link: `https://twitter.com/sgheb`,
    picture: `/speakers/Sacha_Ghebali.jpg`,
  },
  {
    company: `IOVLabs`,
    firstname: `Solange`,
    lastname: `Gueiros`,
    link: `https://www.linkedin.com/in/solangegueiros/`,
    picture: `/speakers/Solange_Gueiros.jpg`,
  },
  {
    company: `Witnet Foundation`,
    firstname: `Claudia`,
    lastname: `Bartoli`,
    link: `https://www.linkedin.com/in/claudia-bartoli/`,
    picture: `/speakers/Claudia_Bartoli.jpg`,
  },
  {
    company: `iExec`,
    firstname: `Gilles`,
    lastname: `Fedak`,
    link: `https://twitter.com/iex_ec`,
    picture: `/speakers/Gilles_Fedak.jpg`,
  },
  {
    company: `Ethereum France`,
    firstname: `Nathan`,
    lastname: `Sexer`,
    link: `https://twitter.com/NathanSexer`,
    picture: `/speakers/Nathan_Sexer.jpg`,
  },
  {
    company: `Fountain`,
    firstname: `Mathieu`,
    lastname: `Chanson`,
    link: `https://www.linkedin.com/in/mathieuchanson/`,
    picture: `/speakers/Mathieu_Chanson.jpg`,
  },
  {
    company: `pNetwork`,
    firstname: `Andrea`,
    lastname: `Fortugno`,
    link: `https://twitter.com/andreafortugno_`,
    picture: `/speakers/Andrea_Fortugno.jpg`,
  },
  {
    company: `Nexo`,
    firstname: `Nikolay`,
    lastname: `Angelov`,
    link: `https://www.linkedin.com/in/thedi/`,
    picture: `/speakers/Nikolay_Angelov.jpg`,
  },
  {
    company: `Visa Research`,
    firstname: `Srinivasan`,
    lastname: `Raghuraman`,
    link: `https://twitter.com/srini131293`,
    picture: `/speakers/Srinivasan_Raghuraman.jpg`,
  },
  {
    company: `Keep Network`,
    firstname: `Sasha`,
    lastname: `Tanase`,
    link: `https://twitter.com/sasha_tanase`,
    picture: `/speakers/Sasha_Tanase.jpg`,
  },
  {
    company: `Democracy Earth Foundation`,
    firstname: `Santiago`,
    lastname: `Siri`,
    link: `https://twitter.com/santisiri`,
    picture: `/speakers/Santiago_Siri.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Barnabe`,
    lastname: `Monnot`,
    link: `https://twitter.com/barnabemonnot`,
    picture: `/speakers/Barnabe_Monnot.jpg`,
  },
  {
    company: `Bitwala`,
    firstname: `Benjamin`,
    lastname: `Jones`,
    link: `https://twitter.com/BenPeterJones`,
    picture: `/speakers/Benjamin_Jones.jpg`,
  },
  {
    company: `Consensys`,
    firstname: `Sajida`,
    lastname: `Zouarhi`,
    link: `https://twitter.com/Saj_JZ`,
    picture: `/speakers/Sajida_Zouarhi.jpg`,
  },
  {
    company: `Gnosis Safe`,
    firstname: `Richard`,
    lastname: `Meissner`,
    link: `https://twitter.com/rimeissner`,
    picture: `/speakers/Richard_Meissner.jpg`,
  },
  {
    company: `Etherplay`,
    firstname: `Ronan`,
    lastname: `Sandford`,
    link: `https://twitter.com/wighawag`,
    picture: `/speakers/Ronan_Sandford.jpg`,
  },
  {
    company: `Amazon Web Services`,
    firstname: `Everton`,
    lastname: `Fraga`,
    link: `https://twitter.com/evertonfraga`,
    picture: `/speakers/Everton_Fraga.jpg`,
  },
  {
    company: `Harvard / CNRS`,
    firstname: `Primavera`,
    lastname: `De filippi`,
    link: `https://twitter.com/yaoeo`,
    picture: `/speakers/Primavera_De_Filippi.jpg`,
  },
  {
    company: `Multis`,
    firstname: `Thibaut`,
    lastname: `Sahaghian`,
    link: `https://www.linkedin.com/in/tsahaghian/`,
    picture: `/speakers/Thibaut_Sahaghian.jpg`,
  },
  {
    company: `Sushi.com`,
    firstname: `Joseph`,
    lastname: `Delong`,
    link: `https://twitter.com/josephdelong`,
    picture: `/speakers/Joseph_Delong.jpg`,
  },
  {
    company: `L2P.finance`,
    firstname: `Alexis`,
    lastname: `Masseron`,
    link: `https://twitter.com/AlexisMasseron`,
    picture: `/speakers/Alexis_Masseron.jpg`,
  },
  {
    company: `Ledger`,
    firstname: `Matt`,
    lastname: `Johnson`,
    link: `https://www.ledger.com/people/matt-johnson`,
    picture: `/speakers/Matt_Johnson.jpg`,
  },
  {
    company: `Ledger`,
    firstname: `Jean`,
    lastname: `Passot`,
    link: `https://www.linkedin.com/in/jean-p-68100312a/`,
    picture: `/speakers/Jean_Passot.jpg`,
  },
  {
    company: `Stake Capital`,
    firstname: `Julien`,
    lastname: `Bouteloup`,
    link: `https://twitter.com/bneiluj`,
    picture: `/speakers/Julien_Bouteloup.jpg`,
  },
  {
    company: `Boson Protocol`,
    firstname: `Holly`,
    lastname: `Atkinson`,
    link: `https://twitter.com/haatkinson`,
    picture: `/speakers/Holly_Atkinson.jpg`,
  },
  {
    company: `rotki`,
    firstname: `Lefteris`,
    lastname: `Karapetsas`,
    link: `https://twitter.com/lefterisjp`,
    picture: `/speakers/Lefteris_Karapetsas.jpg`,
  },
  {
    company: `Paladin`,
    firstname: `Romain`,
    lastname: `Figuereo`,
    link: `https://twitter.com/Figue_me`,
    picture: `/speakers/Romain_Figuereo.jpg`,
  },
  {
    company: `Chainlink`,
    firstname: `Johann`,
    lastname: `Eid`,
    link: `https://twitter.com/EidJohann`,
    picture: `/speakers/Johann_Eid.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `Matheus`,
    lastname: `Alencar`,
    link: `https://twitter.com/mtsalenc`,
    picture: `/speakers/Matheus_Alencar.jpg`,
  },
  {
    company: `Fei Protocol`,
    firstname: `Joey`,
    lastname: `Santoro`,
    link: `https://twitter.com/Joey__Santoro`,
    picture: `/speakers/Joey_Santoro.jpg`,
  },
  {
    company: `ECAN`,
    firstname: `Xavier`,
    lastname: `Lavayssiere`,
    link: `https://twitter.com/xavierlava`,
    picture: `/speakers/Xavier_Lavayssiere.jpg`,
  },
  {
    company: `EidooCard`,
    firstname: `Michele`,
    lastname: `Montecchi`,
    link: `https://www.linkedin.com/in/michele-montecchi-b8025921/`,
    picture: `/speakers/Michele_Montecchi.jpg`,
  },
  {
    company: `Tel Aviv University and Certora`,
    firstname: `Mooly`,
    lastname: `Sagiv`,
    link: `https://twitter.com/SagivMooly`,
    picture: `/speakers/Mooly_Sagiv.jpg`,
  },
  {
    company: `Gelato`,
    firstname: `Hilmar`,
    lastname: `Orth`,
    link: `https://twitter.com/hilmarxo`,
    picture: `/speakers/Hilmar_Orth.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `Plinio`,
    lastname: `Braga`,
    link: `https://twitter.com/pliniobraga_`,
    picture: `/speakers/Plinio_Braga.jpg`,
  },
  {
    company: `MIT Media Lab`,
    firstname: `Daniel`,
    lastname: `Marquez`,
    link: `https://twitter.com/Bumangues92`,
    picture: `/speakers/Daniel_Marquez.jpg`,
  },
  {
    company: `Storj Labs`,
    firstname: `Kevin`,
    lastname: `Leffew`,
    link: `https://www.linkedin.com/in/kevinleffew/`,
    picture: `/speakers/Kevin_Leffew.jpg`,
  },
  {
    company: `Commonwealth Labs`,
    firstname: `Drew`,
    lastname: `Stone`,
    link: `https://twitter.com/drew___stone`,
    picture: `/speakers/Drew_Stone.jpg`,
  },
  {
    company: `Crypto art advisor and collector`,
    firstname: `Fanny`,
    lastname: `Lakoubay`,
    link: `https://twitter.com/flakoubay`,
    picture: `/speakers/Fanny_Lakoubay.jpg`,
  },
  {
    company: `European Investment Fund`,
    firstname: `Rene`,
    lastname: `Andres`,
    link: `https://www.linkedin.com/in/ren%C3%A9-andres-663457aa/`,
    picture: `/speakers/Rene_Andres.jpg`,
  },
  {
    company: `Ethertrust`,
    firstname: `Pascal`,
    lastname: `Urien`,
    link: `https://www.linkedin.com/in/pascal-urien-a491738`,
    picture: `/speakers/Pascal_Urien.jpg`,
  },
  {
    company: `Biconomy `,
    firstname: `Ahmed`,
    lastname: `Al-balaghi`,
    link: `https://twitter.com/arabalaghi`,
    picture: `/speakers/Ahmed_Al-balaghi.jpg`,
  },
  {
    company: `1inch Network`,
    firstname: `Anton`,
    lastname: `Bukov`,
    link: `https://twitter.com/k06a`,
    picture: `/speakers/Anton_Bukov.jpg`,
  },
  {
    company: `Harmony`,
    firstname: `Stephen`,
    lastname: `Tse`,
    link: `https://twitter.com/stse`,
    picture: `/speakers/Stephen_Tse.jpg`,
  },
  {
    company: `Techintern.io`,
    firstname: `Kingsong`,
    lastname: `Chen`,
    link: `https://www.linkedin.com/in/kingsong/`,
    picture: `/speakers/Kingsong_Chen.jpg`,
  },
  {
    company: `Autonomous lawyer`,
    firstname: `Fatemeh`,
    lastname: `Fannizadeh`,
    link: `https://twitter.com/fatalmeh`,
    picture: `/speakers/Fatemeh_Fannizadeh.jpg`,
  },
  {
    company: `Opera`,
    firstname: `Susie`,
    lastname: `Batt`,
    link: `https://www.linkedin.com/in/susiebatt/`,
    picture: `/speakers/Susie_Batt.jpg`,
  },
  {
    company: `TrueBlocks, LLC`,
    firstname: `Thomas-Jay`,
    lastname: `Rush`,
    link: `https://twitter.com/trueblocks`,
    picture: `/speakers/Thomas-Jay_Rush.jpg`,
  },
  {
    company: `Tantra Labs`,
    firstname: `Allison`,
    lastname: `Reichel`,
    link: `https://twitter.com/AllisonReichel`,
    picture: `/speakers/Allison_Reichel.jpg`,
  },
  {
    company: `Filecoin Foundation`,
    firstname: `Marta`,
    lastname: `Belcher`,
    link: `https://twitter.com/martabelcher`,
    picture: `/speakers/Marta_Belcher.jpg`,
  },
  {
    company: `3Box Labs`,
    firstname: `Joel`,
    lastname: `Thorstensson`,
    link: `https://twitter.com/oedth`,
    picture: `/speakers/Joel_Thorstensson.jpg`,
  },
  {
    company: `GoodGhosting`,
    firstname: `Rachel`,
    lastname: `Black`,
    link: `https://twitter.com/rachblondon`,
    picture: `/speakers/Rachel_Black.jpg`,
  },
  {
    company: `Bitfly`,
    firstname: `Stefan`,
    lastname: `Starflinger`,
    link: `https://twitter.com/stefan_star`,
    picture: `/speakers/Stefan_Starflinger.jpg`,
  },
  {
    company: `HOPR`,
    firstname: `Amira`,
    lastname: `Bouguera`,
    link: `https://twitter.com/amirabouguera`,
    picture: `/speakers/Amira_Bouguera.jpg`,
  },
  {
    company: `Polywrap`,
    firstname: `Jordan`,
    lastname: `Ellis`,
    link: `https://twitter.com/polywrap_io`,
    picture: `/speakers/Jordan_Ellis.jpg`,
  },
  {
    company: `Paraswap`,
    firstname: `Shresth`,
    lastname: `Agrawal`,
    link: `https://twitter.com/shresth3103`,
    picture: `/speakers/Shresth_Agrawal.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Austin`,
    lastname: `Griffith`,
    link: `https://twitter.com/austingriffith`,
    picture: `/speakers/Austin_Griffith.jpg`,
  },
  {
    company: `Centrifuge`,
    firstname: `Cassidy`,
    lastname: `Daly`,
    link: `https://twitter.com/cassidydaly`,
    picture: `/speakers/Cassidy_Daly.jpg`,
  },
  {
    company: `Nethermind`,
    firstname: `Tomasz`,
    lastname: `Stanczak`,
    link: `https://twitter.com/tkstanczak`,
    picture: `/speakers/Tomasz_Stanczak.jpg`,
  },
  {
    company: `Oiler Network`,
    firstname: `Victor`,
    lastname: `Naumik`,
    link: `https://twitter.com/vicnaum1`,
    picture: `/speakers/Victor_Naumik.jpg`,
  },
  {
    company: `Brainbot`,
    firstname: `Jannik`,
    lastname: `Luhn`,
    link: `https://twitter.com/AnotherJannik`,
    picture: `/speakers/Jannik_Luhn.jpg`,
  },
  {
    company: `Raiden Network`,
    firstname: `Jacob`,
    lastname: `Czepluch`,
    link: `https://twitter.com/_czepluch`,
    picture: `/speakers/Jacob_Czepluch.jpg`,
  },
  {
    company: `Gnosis`,
    firstname: `Felix`,
    lastname: `Leupold`,
    link: `https://twitter.com/fleupold_`,
    picture: `/speakers/Felix_Leupold.jpg`,
  },
  {
    company: `ConsenSys`,
    firstname: `James`,
    lastname: `Beck`,
    link: `https://twitter.com/jamesjohnbeck`,
    picture: `/speakers/James_Beck.jpg`,
  },
  {
    company: `The Mangrove`,
    firstname: `Vincent`,
    lastname: `Danos`,
    link: `https://twitter.com/vee3my`,
    picture: `/speakers/Vincent_Danos.jpg`,
  },
  {
    company: `MakerDAO`,
    firstname: `Gustav`,
    lastname: `Arentoft`,
    link: `https://twitter.com/GArentoft`,
    picture: `/speakers/Gustav_Arentoft.jpg`,
  },
  {
    company: `Charged Particles`,
    firstname: `Ben`,
    lastname: `Lakoff`,
    link: `https://twitter.com/benlakoff`,
    picture: `/speakers/Ben_Lakoff.jpg`,
  },
  {
    company: `APWine Finance`,
    firstname: `Gaspard`,
    lastname: `Peduzzi`,
    link: `https://twitter.com/GaspardPeduzzi`,
    picture: `/speakers/Gaspard_Peduzzi.jpg`,
  },
  {
    company: `Centrifuge/DoD`,
    firstname: `Helena`,
    lastname: `Flack`,
    link: `https://twitter.com/helsfoftroy`,
    picture: `/speakers/Helena_Flack.jpg`,
  },
  {
    company: `Celo`,
    firstname: `Marek`,
    lastname: `Olszewski`,
    link: `https://twitter.com/marek_`,
    picture: `/speakers/Marek_Olszewski.jpg`,
  },
  {
    company: `Cosmos`,
    firstname: `Peng`,
    lastname: `Zhong`,
    link: `https://twitter.com/zcpeng`,
    picture: `/speakers/Peng_Zhong.jpg`,
  },
  {
    company: `Offshift`,
    firstname: `Alex`,
    lastname: `Shipp`,
    link: `https://twitter.com/AlexShippXFT`,
    picture: `/speakers/Alex_Shipp.jpg`,
  },

  {
    company: `Outlier Ventures`,
    firstname: `Jamie`,
    lastname: `Burke`,
    link: `https://twitter.com/jamie247`,
    picture: `/speakers/Jamie_Burke.jpg`,
  },
  {
    company: `Travala`,
    firstname: `Juan`,
    lastname: `Otero`,
    link: `https://twitter.com/joterovila`,
    picture: `/speakers/Juan_Otero.jpg`,
  },
  {
    company: `Audius`,
    firstname: `Cooper`,
    lastname: `Turley`,
    link: `https://twitter.com/Cooopahtroopa`,
    picture: `/speakers/Cooper_Turley.jpg`,
  },
  {
    company: `TruCol`,
    firstname: `Victoria`,
    lastname: `Bosch`,
    link: `https://www.linkedin.com/in/victoria-bosch-7a9a821a3/`,
    picture: `/speakers/Victoria_Bosch.jpg`,
  },
  {
    company: `Runtime Verification`,
    firstname: `Rikard`,
    lastname: `Hjort`,
    link: `https://twitter.com/rikardhjort`,
    picture: `/speakers/Rikard_Hjort.jpg`,
  },
  {
    company: `Habitat`,
    firstname: `Max`,
    lastname: `Kuck`,
    link: `https://twitter.com/max_kuck`,
    picture: `/speakers/Max_Kuck.jpg`,
  },
  {
    company: `quilt`,
    firstname: `Matt`,
    lastname: `Garnett`,
    link: `https://twitter.com/lightclients`,
    picture: `/speakers/Matt_Garnett.jpg`,
  },
  {
    company: `Reflexer Labs`,
    firstname: `Guillaume`,
    lastname: `Felley`,
    link: `https://twitter.com/guifel_`,
    picture: `/speakers/Guillaume_Felley.jpg`,
  },
  {
    company: `Hop Protocol`,
    firstname: `Chris`,
    lastname: `Whinfrey`,
    link: `https://twitter.com/WhinfreyChris`,
    picture: `/speakers/Chris_Whinfrey.jpg`,
  },
  {
    company: `Hexarchia`,
    firstname: `Carlo`,
    lastname: `Moretti`,
    link: `https://twitter.com/hexarchia`,
    picture: `/speakers/Carlo_Moretti.jpg`,
  },
  {
    company: `Planck`,
    firstname: `Matthew`,
    lastname: `Stephenson`,
    link: `https://twitter.com/stephensonhmatt`,
    picture: `/speakers/Matthew_Stephenson.jpg`,
  },
  {
    company: `Matter Labs`,
    firstname: `Alex`,
    lastname: `Gluchowski`,
    link: `https://twitter.com/Matter Labs`,
    picture: `/speakers/Alex_Gluchowski.jpg`,
  },
  {
    company: `Pocket Network`,
    firstname: `Michael`,
    lastname: `O'rourke`,
    link: `https://twitter.com/o_rourke`,
    picture: `/speakers/Michael_Orourke.jpg`,
  },
  {
    company: `Paradigm`,
    firstname: `Sasha`,
    lastname: `Shilina`,
    link: `https://twitter.com/sshshln`,
    picture: `/speakers/Sasha_Shilina.jpg`,
  },
  {
    company: `Edge & Node`,
    firstname: `Nader`,
    lastname: `Dabit`,
    link: `https://twitter.com/dabit3`,
    picture: `/speakers/Nader_Dabit.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Leo`,
    lastname: `Alt`,
    link: `https://twitter.com/leonardoalt`,
    picture: `/speakers/Leo_Alt.jpg`,
  },
  {
    company: `Bolero Music`,
    firstname: `William`,
    lastname: `Bailey`,
    link: `https://www.linkedin.com/in/william-bailey/`,
    picture: `/speakers/William_Bailey.jpg`,
  },
  {
    company: `Quantstamp`,
    firstname: `Sebastian`,
    lastname: `Banescu`,
    link: `https://twitter.com/banescusebi`,
    picture: `/speakers/Sebastian_Banescu.jpg`,
  },
  {
    company: `HOPR`,
    firstname: `Qianchen`,
    lastname: `Yu`,
    link: `https://twitter.com/qyuqianchen`,
    picture: `/speakers/Qianchen_Yu.jpg`,
  },
  {
    company: `Minespider`,
    firstname: `Ella`,
    lastname: `Cullen`,
    link: `https://www.linkedin.com/in/ellacullen/`,
    picture: `/speakers/Ella_Cullen.jpg`,
  },
  {
    company: `YouHodler`,
    firstname: `Alex`,
    lastname: `Vinny`,
    link: `https://www.linkedin.com/in/alexvinny/`,
    picture: `/speakers/Alex_Vinny.jpg`,
  },
  {
    company: `Ethereum Foundation `,
    firstname: `Josef`,
    lastname: `Je`,
    link: `https://twitter.com/JosefJ_`,
    picture: `/speakers/Josef_Je.jpg`,
  },
  {
    company: `Deep Work`,
    firstname: `Andrej`,
    lastname: `Berlin`,
    link: `https://twitter.com/deepwork_studio`,
    picture: `/speakers/Andrej_Berlin.jpg`,
  },
  {
    company: `SkillZ`,
    firstname: `Laszlo`,
    lastname: `Szabo`,
    link: `https://twitter.com/LaszloSzabo13`,
    picture: `/speakers/Laszlo_Szabo.jpg`,
  },
  {
    company: `Trustlines Network`,
    firstname: `Andreas`,
    lastname: `Fletcher`,
    link: `https://twitter.com/TrustlinesFound`,
    picture: `/speakers/Andreas_Fletcher.jpg`,
  },
  {
    company: `Independent`,
    firstname: `Anuj`,
    lastname: `Das gupta`,
    link: `https://twitter.com/anujdasgupta`,
    picture: `/speakers/Anuj_Das_gupta.jpg`,
  },
  {
    company: `Moonbeam`,
    firstname: `Antoine`,
    lastname: `Estienne`,
    link: `https://fr.linkedin.com/in/antoine-estienne-4b633985`,
    picture: `/speakers/Antoine_Estienne.jpg`,
  },
  {
    company: `Pixelcraft Studios`,
    firstname: `Vincent`,
    lastname: `Tournadre`,
    link: `https://twitter.com/letsgobankless`,
    picture: `/speakers/Vincent_Tournadre.jpg`,
  },
  {
    company: `Anyblock Analytics`,
    firstname: `Yarkin`,
    lastname: `Gocmen`,
    link: `https://www.linkedin.com/in/yarkin-g%C3%B6cmen-674762194/`,
    picture: `/speakers/Yarkin_Gocmen.jpg`,
  },
  {
    company: `Fluence Labs`,
    firstname: `Dmitry`,
    lastname: `Kurinskiy`,
    link: `https://github.com/alari`,
    picture: `/speakers/Dmitry_Kurinskiy.jpg`,
  },
  {
    company: `Injective Protocol`,
    firstname: `Eric`,
    lastname: `Chen`,
    link: `https://twitter.com/ericinjective`,
    picture: `/speakers/Eric_Chen.jpg`,
  },
  {
    company: `Chainsafe`,
    firstname: `Polina`,
    lastname: `Aladina`,
    link: `https://twitter.com/Polycarpik`,
    picture: `/speakers/Polina_Aladina.jpg`,
  },
  {
    company: `Collider.vc`,
    firstname: `Eylon`,
    lastname: `Aviv`,
    link: `https://twitter.com/theeylon`,
    picture: `/speakers/Eylon_Aviv.jpg`,
  },
  {
    company: `Kramer Levin Naftalis Frankel LLP`,
    firstname: `Victor`,
    lastname: `Charpiat`,
    link: `https://www.linkedin.com/in/victor-charpiat-56577a63/`,
    picture: `/speakers/Victor_Charpiat.jpg`,
  },
  {
    company: `Celo`,
    firstname: `James`,
    lastname: `Prestwich`,
    link: `https://twitter.com/_prestwich`,
    picture: `/speakers/James_Prestwich.jpg`,
  },
  {
    company: `Celo`,
    firstname: `Bogdan-radu`,
    lastname: `Dumitru`,
    link: `https://twitter.com/i_bowd`,
    picture: `/speakers/Bogdan_Dumitru.jpg`,
  },
  {
    company: `CertiK`,
    firstname: `Xinyuan`,
    lastname: `Sun`,
    link: `https://twitter.com/sxysun1`,
    picture: `/speakers/Xinyuan_Sun.jpg`,
  },
  {
    company: `Yearn Finance`,
    firstname: `Facu`,
    lastname: `Ameal`,
    link: `https://twitter.com/fameal`,
    picture: `/speakers/Facu_Ameal.jpg`,
  },
  {
    company: `Acala`,
    firstname: `Dan`,
    lastname: `Reecer`,
    link: `https://twitter.com/danreecer_`,
    picture: `/speakers/Dan_Reecer.jpg`,
  },
  {
    company: `Anoma`,
    firstname: `Christopher`,
    lastname: `Goes`,
    link: `https://twitter.com/cwgoes`,
    picture: `/speakers/Christopher_Goes.jpg`,
  },
  {
    company: `Ethermore`,
    firstname: `Dan`,
    lastname: `Stone`,
    link: `https://twitter.com/ethermorelore`,
    picture: `/speakers/Dan_Stone.jpg`,
  },
  {
    company: `BVVentures`,
    firstname: `Matthieu`,
    lastname: `Gueissaz`,
    link: `https://www.linkedin.com/in/matthieu-gueissaz-4a50298b/`,
    picture: `/speakers/Matthieu_Gueissaz.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Rob`,
    lastname: `Stupay`,
    link: `https://twitter.com/ryestew`,
    picture: `/speakers/Rob_Stupay.jpg`,
  },
  {
    company: `Multis`,
    firstname: `Gregoire`,
    lastname: `Jeanmart`,
    link: `https://twitter.com/GregJeanmart`,
    picture: `/speakers/Gregoire_Jeanmart.jpg`,
  },
  {
    company: `Indexed Finance`,
    firstname: `Laurence`,
    lastname: `Day`,
    link: `https://twitter.com/laurence_e_day`,
    picture: `/speakers/Laurence_Day.jpg`,
  },
  {
    company: `ChainSafe Systems`,
    firstname: `Liesl`,
    lastname: `Eichholz`,
    link: `https://twitter.com/liesleichholz`,
    picture: `/speakers/Liesl_Eichholz.jpg`,
  },
  {
    company: `Token Engineering Academy `,
    firstname: `Angela`,
    lastname: `Kreitenweis`,
    link: `https://twitter.com/akrtws`,
    picture: `/speakers/Angela_Kreitenweis.jpg`,
  },
  {
    company: `ORWL Avocats`,
    firstname: `William`,
    lastname: `O'rorke`,
    link: `https://twitter.com/williamororke`,
    picture: `/speakers/William_Ororke.jpg`,
  },
  {
    company: `Permanent Ventures`,
    firstname: `Garrett`,
    lastname: `Macdonald`,
    link: `https://twitter.com/bitcoingarrett`,
    picture: `/speakers/Garrett_Macdonald.jpg`,
  },
  {
    company: `Mattereum.com`,
    firstname: `Vinay`,
    lastname: `Gupta`,
    link: `https://twitter.com/leashless`,
    picture: `/speakers/Vinay_Gupta.jpg`,
  },
  {
    company: `StarkWare`,
    firstname: `Avihu`,
    lastname: `Levy`,
    link: `https://twitter.com/avihu28`,
    picture: `/speakers/Avihu_Levy.jpg`,
  },
  {
    company: `Sigma Prime`,
    firstname: `Mehdi`,
    lastname: `Zerouali`,
    link: `https://twitter.com/ethzed`,
    picture: `/speakers/Mehdi_Zerouali.jpg`,
  },
  {
    company: `netdata`,
    firstname: `Odysseas`,
    lastname: `Lamtzidis`,
    link: `https://twitter.com/odysseas_lam`,
    picture: `/speakers/Odysseas_Lamtzidis.jpg`,
  },
  {
    company: `Ledger`,
    firstname: `Victor`,
    lastname: `Servant`,
    link: `https://twitter.com/yhql6`,
    picture: `/speakers/Victor_Servant.jpg`,
  },
  {
    company: `Nym`,
    firstname: `Jaya klara`,
    lastname: `Brekke`,
    link: `https://twitter.com/jayapapaya`,
    picture: `/speakers/Jaya_Brekke.jpg`,
  },
  {
    company: `ChainSecurity`,
    firstname: `Emilie`,
    lastname: `Raffo`,
    link: `https://www.linkedin.com/in/emilieraffo/`,
    picture: `/speakers/Emilie_Raffo.jpg`,
  },
  {
    company: `THE SANDBOX`,
    firstname: `Sebastien`,
    lastname: `Borget`,
    link: `https://twitter.com/thesandboxgame`,
    picture: `/speakers/Sebastien_Borget.jpg`,
  },
  {
    company: `Aurora Labs`,
    firstname: `Alex`,
    lastname: `Shevchenko`,
    link: `https://twitter.com/AlexAuroraDev`,
    picture: `/speakers/Alex_Shevchenko.jpg`,
  },
  {
    company: `1hive`,
    firstname: `Sacha`,
    lastname: `Saint-leger`,
    link: `https://twitter.com/0xmiel`,
    picture: `/speakers/Sacha_SaintLeger.jpg`,
  },
  {
    company: `MakerDAO`,
    firstname: `Nadia`,
    lastname: `Alvarez`,
    link: `https://twitter.com/nad8802`,
    picture: `/speakers/Nadia_Alvarez.jpg`,
  },
  {
    company: `Ethereum4 by Remix`,
    firstname: `Matteo`,
    lastname: `Tambussi`,
    link: `https://twitter.com/matlepunk`,
    picture: `/speakers/Matteo_Tambussi.jpg`,
  },
  {
    company: `LegalHacker Torino`,
    firstname: `Luigi`,
    lastname: `Cantisani`,
    link: `https://it.linkedin.com/in/luigicantisani`,
    picture: `/speakers/Luigi_Cantisani.jpg`,
  },
  {
    company: `Dfns`,
    firstname: `Clarisse`,
    lastname: `Hagege`,
    link: `https://www.linkedin.com/in/clarissehagege/`,
    picture: `/speakers/Clarisse_Hagege.jpg`,
  },
  {
    company: `Angle`,
    firstname: `Pablo`,
    lastname: `Veyrat`,
    link: `https://www.linkedin.com/in/pablo-veyrat-5a6a84130/`,
    picture: `/speakers/Pablo_Veyrat.jpg`,
  },
  {
    company: `Fuel Labs`,
    firstname: `Alex`,
    lastname: `Hansen`,
    link: `https://twitter.com/awleckss`,
    picture: `/speakers/Alex_Hansen.jpg`,
  },
  {
    company: `SecuRing`,
    firstname: `Damian`,
    lastname: `Rusinek`,
    link: `https://twitter.com/drdr_zz`,
    picture: `/speakers/Damian_Rusinek.jpg`,
  },
  {
    company: `Conreality`,
    firstname: `Dan`,
    lastname: `Komorny`,
    link: `https://twitter.com/DanKomorny`,
    picture: `/speakers/Dan_Komorny.jpg`,
  },
  {
    company: `Regen Network`,
    firstname: `Robert`,
    lastname: `Zaremba`,
    link: `https://www.linkedin.com/in/zarembarobert`,
    picture: `/speakers/Robert_Zaremba.jpg`,
  },
  {
    company: `Gitcoin`,
    firstname: `Kevin`,
    lastname: `Owocki`,
    link: `https://twitter.com/owocki`,
    picture: `/speakers/Kevin_Owocki.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Vlad`,
    lastname: `Zamfir`,
    link: `https://twitter.com/VladZamfir`,
    picture: `/speakers/Vlad_Zamfir.jpg`,
  },
  {
    company: `Swarm & Fair data society`,
    firstname: `Gregor`,
    lastname: `Zavcer`,
    link: `https://twitter.com/jssr`,
    picture: `/speakers/Gregor_Zavcer.jpg`,
  },
  {
    company: `Ethereum Swarm`,
    firstname: `Michelle`,
    lastname: `Thuy`,
    link: `https://twitter.com/michelle_plur`,
    picture: `/speakers/Michelle_Thuy.jpg`,
  },
  {
    company: `skytale.finance `,
    firstname: `Enrico`,
    lastname: `Mariotti`,
    link: `https://twitter.com/enricomar`,
    picture: `/speakers/Enrico_Mariotti.jpg`,
  },
  {
    company: `Swarm`,
    firstname: `Rinke`,
    lastname: `Hendriksen`,
    link: `https://twitter.com/EknirNL`,
    picture: `/speakers/Rinke_Hendriksen.jpg`,
  },
  {
    company: `Pods`,
    firstname: `Robson`,
    lastname: `Silva Junior`,
    link: `https://twitter.com/robsjre`,
    picture: `/speakers/Robson_Silva.jpg`,
  },
  {
    company: `Flashbots`,
    firstname: `Alex`,
    lastname: `Obadia`,
    link: `https://twitter.com/obadiaalex`,
    picture: `/speakers/Alex_Obadia.jpg`,
  },
  {
    company: `Skynet`,
    firstname: `David`,
    lastname: `Vorick`,
    link: `https://twitter.com/DavidVorick`,
    picture: `/speakers/David_Vorick.jpg`,
  },
  {
    company: `Hummingbot`,
    firstname: `Jason`,
    lastname: `Tomlinson`,
    link: `https://www.linkedin.com/in/jason-tomlinson-88b0b78/`,
    picture: `/speakers/Jason_Tomlinson.jpg`,
  },
  {
    company: `Cometh`,
    firstname: `Vincent`,
    lastname: `Le Gallic`,
    link: `https://twitter.com/vincentlg`,
    picture: `/speakers/Vincent_LeGallic.jpg`,
  },
  {
    company: `EthBlockArt`,
    firstname: `Adrian`,
    lastname: `Le Bas`,
    link: `https://twitter.com/adrianleb`,
    picture: `/speakers/Adrian_LeBas.jpg`,
  },
  {
    company: `Gnosis Safe`,
    firstname: `Lukas`,
    lastname: `Schor`,
    link: `https://twitter.com/SchorLukas`,
    picture: `/speakers/Lukas_Schor.jpg`,
  },
  {
    company: `Balancer Labs`,
    firstname: `Jeremy`,
    lastname: `Musighi`,
    link: `https://twitter.com/immutbl`,
    picture: `/speakers/Jeremy_Musighi.jpg`,
  },
  {
    company: `Privy`,
    firstname: `Henri`,
    lastname: `Stern`,
    link: `https://www.linkedin.com/in/henri-stern/`,
    picture: `/speakers/Henri_Stern.jpg`,
  },
  {
    company: `ConsenSys`,
    firstname: `Joseph`,
    lastname: `C`,
    link: `https://twitter.com/josephch`,
    picture: `/speakers/Joseph_C.jpg`,
  },
  {
    company: `Ethernal`,
    firstname: `Antoine`,
    lastname: `De chevigne`,
    link: `https://twitter.com/tryethernal`,
    picture: `/speakers/Antoine_DeChevigne.jpg`,
  },
  {
    company: `Kleros`,
    firstname: `Jimmy`,
    lastname: `Ragosa`,
    link: `https://twitter.com/JimmyRagosa`,
    picture: `/speakers/Jimmy_Ragosa.jpg`,
  },
  {
    company: `Element Finance`,
    firstname: `Charles`,
    lastname: `St.Louis`,
    link: `https://twitter.com/CharlieStLouis`,
    picture: `/speakers/Charles_StLouis.jpg`,
  },
  {
    company: `KONG`,
    firstname: `Cameron`,
    lastname: `Robertson`,
    link: `https://twitter.com/ccamrobertson`,
    picture: `/speakers/Cameron_Robertson.jpg`,
  },
  {
    company: `Quilt`,
    firstname: `Ansgar`,
    lastname: `Dietrich`,
    link: `https://twitter.com/adietrichs`,
    picture: `/speakers/Ansgar_Dietrich.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Piper`,
    lastname: `Merriam`,
    link: `https://github.com/pipermerriam/`,
    picture: `/speakers/Piper_Merriam.jpg`,
  },
  {
    company: `Lido`,
    firstname: `Vasiliy`,
    lastname: `Shapovalov`,
    link: `https://twitter.com/_vshapovalov`,
    picture: `speakers/Vasiliy_Shapovalov.jpg`,
  },
  {
    company: `Spacemesh`,
    firstname: `Lane`,
    lastname: `Rettig`,
    link: `https://twitter.com/lrettig`,
    picture: `speakers/Lane_Rettig.jpg`,
  },
  {
    company: `ParaSwap`,
    firstname: `Mounir`,
    lastname: `Benchemled`,
    link: `https://twitter.com/mounibec`,
    picture: `speakers/Mounir_Benchemled.jpg`,
  },
  {
    company: `EUCI / ADAN`,
    firstname: `Simon`,
    lastname: `Polrot`,
    link: `https://twitter.com/simonpolrot`,
    picture: `speakers/Simon_Polrot.jpg`,
  },
  {
    company: `Sorare`,
    firstname: `Brian O'Hagan`,
    lastname: `O'hagan`,
    link: `https://twitter.com/bruhagan`,
    picture: `speakers/Brian_Ohagan.jpg`,
  },
  {
    company: `Sorare`,
    firstname: `Pierre`,
    lastname: `Duperrin`,
    link: `https://twitter.com/pdup56`,
    picture: `speakers/Pierre_Duperrin.jpg`,
  },
  {
    company: `Gnosis Safe`,
    firstname: `Auryn`,
    lastname: `Macmillan`,
    link: `https://twitter.com/auryn_macmillan`,
    picture: `speakers/Auryn_Macmillan.jpg`,
  },
  {
    company: `Common Stacks`,
    firstname: `Griff`,
    lastname: `Green`,
    link: `https://twitter.com/thegrifft`,
    picture: `speakers/Griff_Green.jpg`,
  },
  {
    company: `ConsenSys`,
    firstname: `Steven`,
    lastname: `Haft`,
    link: `https://linkedin.com/in/stevenhaft/`,
    picture: `speakers/Steven_Haft.jpg`,
  },
  {
    company: `Nethermind`,
    firstname: `Marcello`,
    lastname: `Bardus`,
    link: `https://twitter.com/BardusMarcello`,
    picture: `speakers/Marcello_Bardus.jpg`,
  },
  {
    company: `Interchain Foundation`,
    firstname: `Charly`,
    lastname: `Fei`,
    link: `https://twitter.com/charleenfei`,
    picture: `speakers/Charly_Fei.jpg`,
  },
  {
    company: `ConsenSys Diligence`,
    firstname: `Goncalo`,
    lastname: `Sa`,
    link: `https://twitter.com/consensysaudits`,
    picture: `speakers/Goncalo_Sa.jpg`,
  },
  {
    company: `ConsenSys Diligence`,
    firstname: `Joran`,
    lastname: `Honig`,
    link: `https://twitter.com/consensysaudits`,
    picture: `speakers/Joran_Honig.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Aya`,
    lastname: `Miyaguchi`,
    link: `https://twitter.com/ayamiyagotchi`,
    picture: `speakers/Aya_Miyaguchi.jpg`,
  },
  {
    company: `The Graph`,
    firstname: `Yaniv`,
    lastname: `Tal`,
    link: `https://twitter.com/yanivgraph`,
    picture: `speakers/Yaniv_Tal.jpg`,
  },
  {
    company: `The Graph Foundation`,
    firstname: `Eva`,
    lastname: `Beylin`,
    link: `https://twitter.com/evabeylin`,
    picture: `speakers/Eva_Beylin.jpg`,
  },
  {
    company: `ConsenSys`,
    firstname: `Robert`,
    lastname: `Drost`,
    link: `https://www.linkedin.com/in/rjdrost/`,
    picture: `speakers/Robert_Drost.jpg`,
  },
  {
    company: `Uniswap Labs`,
    firstname: `Ashleigh`,
    lastname: `Schap`,
    link: `https://twitter.com/ashleighschap`,
    picture: `speakers/Ashleigh_Schap.jpg`,
  },
  {
    company: `Ethereum France & Cometh`,
    firstname: `Jerome`,
    lastname: `De Tychey`,
    link: `https://twitter.com/jdetychey`,
    picture: `speakers/Jerome_Detychey.jpg`,
  },
  {
    company: `Status`,
    firstname: `Franck`,
    lastname: `Royer`,
    link: `https://twitter.com/dantounet`,
    picture: `speakers/Franck_Royer.jpg`,
  },
  {
    company: `ConsenSys Diligence / Concordia University`,
    firstname: `Shayan`,
    lastname: `Eskandari`,
    link: `https://shayan.es`,
    picture: `/speakers/Shayan_Eskandari.jpg`,
  },
  {
    company: `Near Protocol`,
    firstname: `Daniella`,
    lastname: `Osorio`,
    link: `https://twitter.com/WaverlyMaven`,
    picture: `/speakers/Daniella_Osorio.jpg`,
  },
  {
    company: `Ethereum Foundation`,
    firstname: `Guillaume`,
    lastname: `Ballet`,
    link: ``,
    picture: `/speakers/Guillaume_Ballet.jpg`,
  },
];
